### ISSUE TITLE
🐛 Small bug - "Latest Rules" widget gives double slash /

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Widget#22]
Cc: @lukecookssw @adamcogan 

Hi team, 

### Describe the Bug

Luke found that the links from "Latest Rules" widget have a duplicated slash in them:
<img width="1057" alt="Screen Shot 2022-03-18 at 11 32 40 AM" src="https://user-images.githubusercontent.com/12601228/159062941-ebda5632-13a1-4046-9965-9eea0a471545.png">

The links work so I'm calling this a small bug :)

### To Reproduce
1. Go to [https://www.ssw.com.au/rules](https://www.ssw.com.au/rules/)
2. Hover any link on the sidebar "Latest Rules"
3. See error on links

### Expected Behavior
- https://www.ssw.com.au/rules//is-site-encrypted
should be
- https://www.ssw.com.au/rules/is-site-encrypted

### Tasks
- [ ] Fix

Thanks!

**Comment by JackDevAU** [comment]
This was fixed with #23
