### ISSUE TITLE
✨ Handle when there are no rules

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Rules.Widget#29]
cc @tiagov8 

Hey @BrookJeynes 

As discussed in https://github.com/SSWConsulting/SSW.People/issues/369#issuecomment-1456946329
Right now when there are no rules, the widget is just an empty list.

```[tasklist]
### Tasks
- [ ] Ask designers if its better to hide the entire widget, or show a message e.g. "No rules :("
- [ ] Implement
```

**Comment by JackDevAU** [comment]
Done - this is now fixed with the new widget
