### ISSUE TITLE
🐛 Bug ❌-  "Latest Rules" not showing up on people profile

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.Rules.Widget#30]
Cc: @bradystroud @william-liebenberg @adamcogan @BrookJeynes 

Hi Team

### Describe the Bug
On the people profile, I'm not able to see my Latest Rules since I created a new rule.

### To Reproduce
1. Go to https://ssw.com.au/people/aman-kumar/
2. Scroll down to the Latest Rule

### Expected Behavior

It should show the following rules: 

1. https://ssw.com.au/rules/fork-vs-branch/
2. https://ssw.com.au/rules/placeholder-for-replaceable-text/  
3. https://ssw.com.au/rules/use-google-tag-manager/

### Tasks
- [ ] Investigate 
- [ ] Fix

### Screenshot

<img width="1133" alt="PeopleProfileLatestRule" src="https://user-images.githubusercontent.com/71385247/223288092-17c21a92-1caa-4732-81a9-632f49a28d3b.png">

**Figure: Latest Rules not showing up on the page**

Thanks!

**Comment by SofieHong** [comment]
I also meet this problem:
I edited the rule: https://www.ssw.com.au/rules/video-editing-terms/
But it doesn't show on my SSW People page: https://ssw.com.au/people/sofie-hong

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/108442257/227840033-8e6c805a-751f-4970-8372-0119710fa261.png">

**Comment by Aibono1225** [comment]
As per my conversation with @bradystroud , we need to complete this refactor first before resolving this issue. 💪https://github.com/SSWConsulting/SSW.Rules/issues/786

**Comment by Aibono1225** [comment]
Hi All,

Reason of this issue: Even if the rule is modified, if someone later changes the file's name, the latest rule won't show up on people's profiles.
As discussed with @bradystroud , this problem cannot be solved right now with the current widget-history.json. 😔
