### ISSUE TITLE
Ensure all projects relying on the rules widget are using the latest version

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.Rules.Widget#45]
With the package being upgraded every so often, we need to ensure all our projects are using the latest version.

```[tasklist]
### Tasks
- [x] Ensure Rules is running the latest package version
- [x] Ensure People is running the latest package version
```

**Comment by BrookJeynes** [comment]
This PR should update Rules to the latest version of the widget (1.6.0) https://github.com/SSWConsulting/SSW.Rules/pull/1123

**Comment by BrookJeynes** [comment]
This PR should update People to the latest version of the widget (1.6.0) https://github.com/SSWConsulting/SSW.People/pull/551

**Comment by JackDevAU** [comment]
latest is `1.6.2`

**Comment by BrookJeynes** [comment]
This PR should update People to the latest version of the widget (1.6.2) https://github.com/SSWConsulting/SSW.Rules/pull/1141
