### ISSUE TITLE
Optimise styling for use in other websites

### ISSUE THREAD

**Issue by taineriley1** [SSWConsulting/SSW.Rules.Widget#6]
@adamcogan @pierssinclairssw @bradystroud 

Hi,

As per my conversation with Piers, the widget's styling is not optimised properly for display in other websites.

![image](https://user-images.githubusercontent.com/40375803/132814826-81a92327-e2b5-4226-982b-47728e8c3c6d.png)
**Figure: Widget installed in the Rules sidebar locally**

Notable improvements from this example are:
- 'Latest Rules' is too big
- SSW Logo is too big
- Rule titles are not left aligned
- Timestamp text does not wrap underneath like intended

![image](https://user-images.githubusercontent.com/40375803/132815314-4926bc49-2906-45f9-8f25-0c1f038e3212.png)
**Figure: Example of left aligned text and timestamp wrapping underneath**

- [ ] Improve the CSS styling of the widget to look better in other sites

**Comment by JackDevAU** [comment]
Closing as the styling of the widget has improved 💪
